/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
/** ID lister. */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 1;
  /** RegularExpression Id. */
  int TRUE = 2;
  /** RegularExpression Id. */
  int FALSE = 3;
  /** RegularExpression Id. */
  int Num = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int TIMES = 7;
  /** RegularExpression Id. */
  int DIV = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int LTE = 12;
  /** RegularExpression Id. */
  int LT = 13;
  /** RegularExpression Id. */
  int GTE = 14;
  /** RegularExpression Id. */
  int GT = 15;
  /** RegularExpression Id. */
  int EQ = 16;
  /** RegularExpression Id. */
  int DIFF = 17;
  /** RegularExpression Id. */
  int LPAR = 18;
  /** RegularExpression Id. */
  int RPAR = 19;
  /** RegularExpression Id. */
  int LCURLY = 20;
  /** RegularExpression Id. */
  int RCURLY = 21;
  /** RegularExpression Id. */
  int EQUALS = 22;
  /** RegularExpression Id. */
  int DOTCOMMA = 23;
  /** RegularExpression Id. */
  int Id = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"let\"",
    "\"true\"",
    "\"false\"",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "<Id>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
